#!/bin/bash

# Makes binary hk the default version.
# It must have been published already.

set -e

if test -z "$HKURL"
then HKURL=https://hk.heroku.com
fi

eval $(go tool dist env)
ver=$(./hk version)
curl -nd $ver $HKURL/hk-$GOOS-$GOARCH
