#!/bin/bash

# Takes the current version at github.com/downloads/kr/hk
# and makes a diff between that and the local hk binary.

set -e

eval $(go tool dist env)
url=https://hk.heroku.com/$GOOS-$GOARCH

rawsha1() {
	python -c 'from hashlib import sha1; import sys; sys.stdout.write(sha1(sys.stdin.read()).digest())'
}

hkdiff() {
	old=$1
	new=$2
	printf hkDIFF01
	rawsha1 <$old
	rawsha1 <$new
	bsdiff $old $new /tmp/hkdiff
	rawsha1 </tmp/hkdiff
	cat /tmp/hkdiff
	rm /tmp/hkdiff
}

mkpatchver() {
	oldver=$1
	echo Fetching $oldver
	wget -qO- $url/$oldver/hk.gz|zcat >hk.old.$oldver
	chmod +x hk.old.$oldver
	echo Patching hk $oldver to $newver
	patch=$GOOS-$GOARCH-$oldver-next.hkdiff
	hkdiff hk.old.$oldver hk >$patch
	rm hk.old.$oldver
}

newver=$(./hk version)

for v in $*
do test $v = $newver &&  { echo new ver matches an old ver; exit 1; }
done

for v in $*
do mkpatchver $v
done

cp hk $GOOS-$GOARCH-hk-$newver
gzip -9 $GOOS-$GOARCH-hk-$newver
