#!/bin/bash

# Publishes binary hk to the distribution app.
# Does not make this version the default.

set -e

if test -z "$HKURL"
then HKURL=https://hk.heroku.com
fi

eval $(go tool dist env)
ver=$(./hk version)
curl -nsT hk $HKURL/hk-$ver-$GOOS-$GOARCH
